# BEGIN MANUAL CUSTOMIZATION
#

# Note that there are two versions of Boost.Process: V1 and V2. As of Boost
# 1.91.0, V2 is the default: it is included via <boost/process.hpp> (and the
# individual <boost/process/*.hpp> headers), while V1 has been relegated to
# <boost/process/v1.hpp> (and the boost/process/v1/ subtree). The
# <boost/process/v2.hpp> umbrella header no longer exists. (See src/buildfile
# for the library targets.)

# The V1 headers (header-only library). Included via <boost/process/v1.hpp>.
#
pub_hdrs_v1 = process/hxx{v1} process/v1/{hxx ixx txx}{**}

# The V2 headers (compiled library): everything except the V1 subtree above.
# Included via <boost/process.hpp> and the individual <boost/process/*.hpp>
# headers.
#
pub_hdrs_v2 = hxx{process} process/{hxx ixx txx}{** -v1 -v1/**}

./: $pub_hdrs_v1 $pub_hdrs_v2

#
# END MANUAL CUSTOMIZATION

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
