import intf_libs  = libboost-asio%lib{boost_asio}
import intf_libs += libboost-assert%lib{boost_assert}
import intf_libs += libboost-beast%lib{boost_beast}
import intf_libs += libboost-container%lib{boost_container}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-endian%lib{boost_endian}
import intf_libs += libboost-random%lib{boost_random}
import intf_libs += libboost-range%lib{boost_range}
import intf_libs += libboost-smart-ptr%lib{boost_smart_ptr}
import intf_libs += libboost-system%lib{boost_system}
import intf_libs += libboost-type-traits%lib{boost_type_traits}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_mqtt5}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_mqtt5}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
