import intf_libs  = libboost-config%lib{boost_config}
import intf_libs += libboost-function-types%lib{boost_function_types}
import intf_libs += libboost-mpl%lib{boost_mpl}
import intf_libs += libboost-preprocessor%lib{boost_preprocessor}
import intf_libs += libboost-type-traits%lib{boost_type_traits}

lib{boost_tti}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_tti}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
