import intf_libs  = libboost-any%lib{boost_any}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-detail%lib{boost_detail}
import intf_libs += libboost-function%lib{boost_function}
import intf_libs += libboost-iterator%lib{boost_iterator}
import intf_libs += libboost-lexical-cast%lib{boost_lexical_cast}
import intf_libs += libboost-smart-ptr%lib{boost_smart_ptr}
import intf_libs += libboost-static-assert%lib{boost_static_assert}
import intf_libs += libboost-throw-exception%lib{boost_throw_exception}
import intf_libs += libboost-type-traits%lib{boost_type_traits}
import impl_libs  = libboost-bind%lib{boost_bind}
import impl_libs += libboost-tokenizer%lib{boost_tokenizer}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

# Public headers.
#
pub = [dir_path] ../include/boost/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{boost_program_options}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{boost_program_options}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmi  obj }{*}: cxx.poptions += -DBOOST_PROGRAM_OPTIONS_SOURCE
obja{*}: cxx.poptions += -DBOOST_PROGRAM_OPTIONS_STATIC_LINK
objs{*}: cxx.poptions += -DBOOST_PROGRAM_OPTIONS_DYN_LINK

# Export options.
#
lib{boost_program_options}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                         -DBOOST_PROGRAM_OPTIONS_NO_LIB
  cxx.export.libs = $intf_libs
}

liba{boost_program_options}: cxx.export.poptions += -DBOOST_PROGRAM_OPTIONS_STATIC_LINK
libs{boost_program_options}: cxx.export.poptions += -DBOOST_PROGRAM_OPTIONS_DYN_LINK

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{boost_program_options}: bin.lib.version = "-$version.project_id"
else
  lib{boost_program_options}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
