import intf_libs  = libboost-align%lib{boost_align}
import intf_libs += libboost-array%lib{boost_array}
import intf_libs += libboost-assert%lib{boost_assert}
import intf_libs += libboost-bind%lib{boost_bind}
import intf_libs += libboost-chrono%lib{boost_chrono}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-date-time%lib{boost_date_time}
import intf_libs += libboost-function%lib{boost_function}
import intf_libs += libboost-regex%lib{boost_regex}
import intf_libs += libboost-smart-ptr%lib{boost_smart_ptr}
import intf_libs += libboost-system%lib{boost_system}
import intf_libs += libboost-throw-exception%lib{boost_throw_exception}
import intf_libs += libboost-type-traits%lib{boost_type_traits}
import intf_libs += libboost-utility%lib{boost_utility}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_asio}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

# BEGIN MANUAL CUSTOMIZATION
#

lib{boost_asio}: cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"

if ($cxx.target.class == 'windows')
  lib{boost_asio}: cxx.export.poptions += -DBOOST_ASIO_NO_DEFAULT_LINKED_LIBS

lib{boost_asio}: cxx.export.libs = $intf_libs

switch $cxx.target.class, $cxx.target.system
{
  case 'windows', 'mingw32'
  {
    lib{boost_asio}: cxx.libs += -lws2_32 -lmswsock
    lib{boost_asio}: cxx.export.libs += -lws2_32 -lmswsock
  }
  case 'windows'
  {
    lib{boost_asio}: cxx.libs += ws2_32.lib mswsock.lib
    lib{boost_asio}: cxx.export.libs += ws2_32.lib mswsock.lib
  }
}

#
# END MANUAL CUSTOMIZATION

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
