intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/boost/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{boost_chrono}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{boost_chrono}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmia obja}{*}: cxx.poptions += -DBOOST_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DBOOST_SHARED_BUILD

# BEGIN MANUAL CUSTOMIZATION
#

switch $cxx.target.class, $cxx.target.system
{
  case 'linux'
    cxx.libs += -lrt -lpthread
  case 'bsd', 'freebsd'
    cxx.libs += -lrt
}

#
# END MANUAL CUSTOMIZATION

# Export options.
#
lib{boost_chrono}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{boost_chrono}: cxx.export.poptions += -DBOOST_STATIC
libs{boost_chrono}: cxx.export.poptions += -DBOOST_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{boost_chrono}: bin.lib.version = "-$version.project_id"
else
  lib{boost_chrono}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
