pub_hdrs = {hxx ixx txx}{**} file{**.h}

./: $pub_hdrs

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*} file{*.h}:
{
  install         = include/boost/
  install.subdirs = true
}
