import intf_libs  = libboost-config%lib{boost_config}
import intf_libs += libboost-mp11%lib{boost_mp11}
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{boost_variant2}: {hxx}{**} $impl_libs $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_variant2}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
