import intf_libs  = libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-mp11%lib{boost_mp11}
import intf_libs += libboost-serialization%lib{boost_serialization}
import intf_libs += libboost-throw-exception%lib{boost_throw_exception}
import intf_libs += libboost-variant2%lib{boost_variant2}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_histogram}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_histogram}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
