import intf_libs  = libboost-any%lib{boost_any}
import intf_libs += libboost-assert%lib{boost_assert}
import intf_libs += libboost-bind%lib{boost_bind}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-format%lib{boost_format}
import intf_libs += libboost-iterator%lib{boost_iterator}
import intf_libs += libboost-mpl%lib{boost_mpl}
import intf_libs += libboost-multi-index%lib{boost_multi_index}
import intf_libs += libboost-optional%lib{boost_optional}
import intf_libs += libboost-range%lib{boost_range}
import intf_libs += libboost-serialization%lib{boost_serialization}
import intf_libs += libboost-static-assert%lib{boost_static_assert}
import intf_libs += libboost-throw-exception%lib{boost_throw_exception}
import intf_libs += libboost-type-traits%lib{boost_type_traits}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_property_tree}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_property_tree}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
