intf_libs = # Interface dependencies.

# BEGIN MANUAL CUSTOMIZATION
#
if $config.libboost_spirit.classic_regex
  import classic_intf_libs = libboost-regex%lib{boost_regex}

if ($config.libboost_spirit.x2 || $config.libboost_spirit.x3)
  import x2x3_intf_libs = libboost-regex%lib{boost_regex}
#
# END MANUAL CUSTOMIZATION
#import xxxx_libs += libhello%lib{hello}

# @@ Only add files if component is enabled.
#
lib{boost_spirit}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_spirit}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
