intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/boost/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{boost-locale}: $pub/{$pub_hdrs}

# BEGIN MANUAL CUSTOMIZATION
#

windows = ($cxx.target.class == 'windows')

# Private headers and sources as well as dependencies.
#
lib{boost_locale}: {hxx ixx txx}{**}                                            \
                   cxx{** -boost/locale/posix/** -boost/locale/win32/**}        \
                   $impl_libs $intf_libs

lib{boost_locale}: boost/locale/win32/cxx{**}: include = $windows
lib{boost_locale}: boost/locale/posix/cxx{**}: include = (! $windows)

#
# END MANUAL CUSTOMIZATION

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

# BEGIN MANUAL CUSTOMIZATION
#

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                -DBOOST_LOCALE_WITH_ICU=1

if $windows
  cxx.poptions += -DBOOST_LOCALE_NO_POSIX_BACKEND       \
                  -D_CRT_SECURE_NO_WARNINGS             \
                  -D_SCL_SECURE_NO_WARNINGS
else
  cxx.poptions += -DBOOST_LOCALE_NO_WINAPI_BACKEND

{hbmia obja}{*}: cxx.poptions += -DBOOST_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DBOOST_SHARED_BUILD

# These two source files don't define BOOST_LOCALE_SOURCE.
#
# @@ TODO Remove this when the fix for
#    https://github.com/boostorg/locale/issues/145 is released.
#
obj{boost/locale/shared/mo_lambda boost/locale/icu/formatters_cache}: \
  cxx.poptions += -DBOOST_LOCALE_SOURCE

#
# END MANUAL CUSTOMIZATION

# Export options.
#
lib{boost-locale}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{boost-locale}: cxx.export.poptions += -DBOOST_STATIC
libs{boost-locale}: cxx.export.poptions += -DBOOST_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{boost-locale}: bin.lib.version = "-$version.project_id"
else
  lib{boost-locale}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
