intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/boost/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{boost-regex}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{boost-regex}: {hxx ixx txx h cxx c}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cc.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
               "-I$out_pfx_inc" "-I$src_pfx_inc"

# BEGIN MANUAL CUSTOMIZATION
#

# BOOST_HAS_ICU must be defined because we're linking against ICU.
#
# Note that this macro is specific to Boost.Regex and therefore violates the
# convention of prefixing library-specific macros with `BOOST_<lib>_`.
#
{hbmi obj}{*}: cc.poptions += -DBOOST_HAS_ICU

#
# END MANUAL CUSTOMIZATION

{hbmia obja}{*}: cc.poptions += -DBOOST_STATIC_BUILD
{hbmis objs}{*}: cc.poptions += -DBOOST_SHARED_BUILD

# Export options.
#
lib{boost-regex}:
{
  cc.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cc.export.libs = $intf_libs
}

liba{boost-regex}: cc.export.poptions += -DBOOST_STATIC
libs{boost-regex}: cc.export.poptions += -DBOOST_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{boost-regex}: bin.lib.version = @"-$version.project_id"
else
  lib{boost-regex}: bin.lib.version = @"-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx h}{*}: install = false
