intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{boost-asio}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

# BEGIN MANUAL CUSTOMIZATION
#

lib{boost-asio}: cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
lib{boost-asio}: cxx.export.libs = $intf_libs

if ($cxx.target.class == 'windows')
{
  lib{boost-asio}: cxx.export.poptions += -DBOOST_ASIO_NO_DEFAULT_LINKED_LIBS

  if ($cxx.target.system == 'mingw32')
  {
    lib{boost-asio}: cxx.libs += -lws2_32 -lmswsock
    lib{boost-asio}: cxx.export.libs += -lws2_32 -lmswsock
  }
  else
  {
    lib{boost-asio}: cxx.libs += ws2_32.lib mswsock.lib
    lib{boost-asio}: cxx.export.libs += ws2_32.lib mswsock.lib
  }
}
else
{
  lib{boost-asio}: cxx.libs += -pthread
  lib{boost-asio}: cxx.export.libs += -pthread
}

#
# END MANUAL CUSTOMIZATION

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
