intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{boost_parser}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_parser}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# BEGIN MANUAL CUSTOMIZATION
#

# Work around bug in libc++ <19 (see README-DEV).
#
if ($cxx.id == 'clang')
  lib{boost_parser}: cxx.export.poptions += -DBOOST_PARSER_DISABLE_CONCEPTS

#
# END MANUAL CUSTOMIZATION

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
