import intf_libs  = libboost-assert%lib{boost_assert}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-throw-exception%lib{boost_throw_exception}
import intf_libs += libboost-type-traits%lib{boost_type_traits}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_uuid}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_uuid}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# BEGIN MANUAL CUSTOMIZATION
#

if ($cxx.target.class == 'windows')
{
  bcrypt = ($cxx.target.system == 'mingw32' ? -lbcrypt : bcrypt.lib)

  lib{boost_uuid}:
  {
    cxx.libs        += $bcrypt
    cxx.export.libs += $bcrypt
  }
}

#
# END MANUAL CUSTOMIZATION

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
