pub_hdrs = hxx{** **.h} {ixx txx}{**}

./: $pub_hdrs

hxx{export}@./: cxx.importable = false

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
