intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{boost_date_time}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_date_time}:
{
  # BEGIN MANUAL CUSTOMIZATION
  #

  # Boost.Date_Time requires BOOST_DATE_TIME_NO_LIB, which disables
  # auto-linking, despite it being header-only, which is unconventional. Most
  # likely this is a result of it only recently having switched from compiled
  # to header-only. (The online docs are apparently outdated so see
  # build/Jamfile.v2 and https://github.com/boostorg/date_time/issues/134
  # regarding the switch to header-only.)
  #
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx" \
                        -DBOOST_DATE_TIME_NO_LIB

  #
  # END MANUAL CUSTOMIZATION

  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
