import intf_libs  = libboost-hana%lib{boost_hana}
import intf_libs += libboost-preprocessor%lib{boost_preprocessor}
import intf_libs += libboost-type-index%lib{boost_type_index}

lib{boost_yap}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_yap}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
