import intf_libs  = libboost-config%lib{boost_config}
import intf_libs += libboost-detail%lib{boost_detail}
import intf_libs += libboost-logic%lib{boost_logic}

lib{boost_numeric_interval}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_numeric_interval}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
