import intf_libs  = libboost-any%lib{boost_any}
import intf_libs += libboost-assert%lib{boost_assert}
import intf_libs += libboost-bind%lib{boost_bind}
import intf_libs += libboost-circular-buffer%lib{boost_circular_buffer}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-function%lib{boost_function}
import intf_libs += libboost-fusion%lib{boost_fusion}
import intf_libs += libboost-mpl%lib{boost_mpl}
import intf_libs += libboost-parameter%lib{boost_parameter}
import intf_libs += libboost-phoenix%lib{boost_phoenix}
import intf_libs += libboost-preprocessor%lib{boost_preprocessor}
import intf_libs += libboost-proto%lib{boost_proto}
import intf_libs += libboost-serialization%lib{boost_serialization}
import intf_libs += libboost-tuple%lib{boost_tuple}
import intf_libs += libboost-type-traits%lib{boost_type_traits}
import intf_libs += libboost-typeof%lib{boost_typeof}

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

lib{boost_msm}: {hxx ixx txx}{**} $intf_libs

# Export options.
#
out_pfx = [dir_path] $out_root/include/
src_pfx = [dir_path] $src_root/include/

lib{boost_msm}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

# Install into the boost/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/boost/
  install.subdirs = true
}
