import intf_libs  = libboost-any%lib{boost_any}
import intf_libs += libboost-assert%lib{boost_assert}
import intf_libs += libboost-config%lib{boost_config}
import intf_libs += libboost-core%lib{boost_core}
import intf_libs += libboost-exception%lib{boost_exception}
import intf_libs += libboost-function%lib{boost_function}
import intf_libs += libboost-function-types%lib{boost_function_types}
import intf_libs += libboost-mpl%lib{boost_mpl}
import intf_libs += libboost-optional%lib{boost_optional}
import intf_libs += libboost-preprocessor%lib{boost_preprocessor}
import intf_libs += libboost-smart-ptr%lib{boost_smart_ptr}
import intf_libs += libboost-static-assert%lib{boost_static_assert}
import intf_libs += libboost-thread%lib{boost_thread}
import intf_libs += libboost-type-traits%lib{boost_type_traits}
import intf_libs += libboost-typeof%lib{boost_typeof}
import intf_libs += libboost-utility%lib{boost_utility}
impl_libs = # Implementation dependencies.

intf_libs = $cxx.deduplicate_export_libs($intf_libs)

# Public headers.
#
pub = [dir_path] ../include/boost/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{boost_contract}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{boost_contract}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

obja{*}: cxx.poptions += -DBOOST_CONTRACT_STATIC_LINK
objs{*}: cxx.poptions += -DBOOST_CONTRACT_DYN_LINK

# Export options.
#
lib{boost_contract}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                         -DBOOST_CONTRACT_NO_LIB
  cxx.export.libs = $intf_libs
}

liba{boost_contract}: cxx.export.poptions += -DBOOST_CONTRACT_STATIC_LINK
libs{boost_contract}: cxx.export.poptions += -DBOOST_CONTRACT_DYN_LINK

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{boost_contract}: bin.lib.version = "-$version.project_id"
else
  lib{boost_contract}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
